regions:
  - all
 
resource-types:
  includes:
    - VirtualNetwork
    - NetworkSecurityGroup
    - PublicIpAddress
    - NetworkInterface
    - VirtualMachine
  excludes:
    - StorageAccount
    - Loganalytics Workspace
 
accounts:
  __AZURE_TENANT_ID__:
    filters:
      ResourceGroup:
        - "rg-monitoring"
        - "rg-shared"
