regions:
  - all
 
resource-types:
  includes:
    - VirtualMachine
    - StorageAccount
    - KeyVault
    - VirtualNetwork
 
accounts:
  __AZURE_TENANT_ID__:
    filters:
      ResourceGroup:
        - "rg-monitoring"
        - "rg-shared"
